apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "config-syncer.fullname" . }}
  labels:
    {{- include "config-syncer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "config-syncer.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "config-syncer.fullname" . }}
  namespace: {{ include "config-syncer.namespace" . }}
