kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "config-syncer.fullname" . }}
  labels:
    {{- include "config-syncer.labels" . | nindent 4 }}
data:
  config-syncer.yaml: |
{{- tpl .Values.config . | nindent 4 }}

